maintainers:
- github: lilydjwg
update_on:
- source: github
  github: meganz/MEGAcmd
  use_latest_tag: true
  query: Linux
- alias: icu
pre_build_script: |
  git_pkgbuild_commit(_G.newver)
post_build_script: git_pkgbuild_commit
