[[library]]
name = "libcmumps"
file = "libcmumps_seq.so"

[[library]]
name = "libdmumps"
file = "libdmumps_seq.so"

[[library]]
name = "libsmumps"
file = "libsmumps_seq.so"

[[library]]
name = "libzmumps"
file = "libzmumps_seq.so"

[[library]]
name = "libcmumps64"
file = "libcmumps64_seq.so"

[[library]]
name = "libdmumps64"
file = "libdmumps64_seq.so"

[[library]]
name = "libsmumps64"
file = "libsmumps64_seq.so"

[[library]]
name = "libzmumps64"
file = "libzmumps64_seq.so"
